### ISSUE TITLE
Introduce new api for computational service

### ISSUE THREAD

**Issue by sunfish-prj** [sunfish-prj/Service-Ledger#2] opened 2017-08-18 16:29 UTC
Add API to offer computational service, aka execution of code

**Comment by andreamargheri** [comment] 2017-09-04 09:05
The Distributed Infrastructure underlying a FaaS federation makes available an API offering a *computational service*. The API has to be technology-agnostic thus to be implemented via any back-end techniques. 

The propose API takes the following arguments 
- **serviceID**: identifier of the requested computational *service*
- **functionID**: identifier of the *function* within the *service* to invoke
- **argument**: list of *invocation arguments* for the function to invoke

The API implementation depends on the used technology. In the case of Hyperledger chain-code, we have the following correspondences: 
- *serviceID* == *chain-code name*
- **functionID** == *function of the chain-code*
- **argument** == *arguments for the chain-code*

**Comment by derigo88** [comment] 2017-09-04 10:04
In the case of MongoDB, we have the following correspondences:

- **serviceID** == _mongo_
- **functionID** == _get/put_
- **argument** == _key/key,value_

**Comment by andreamargheri** [comment] 2017-09-04 11:30
*Get* and *Put*  API would remain as-is. MongoDB would not implement the computational service API. If required, we might implement part of functionality with MongoDB procedure.

**Comment by RunshanHu** [comment] 2017-11-03 16:34
I implemented a series of computation APIs for service ledger, a.k.a. setupLedger (hyperledger enviroment and network setting up), installChaincode, initChaincode and invokeChaincode. However, they all need a json web token as a parameter every time you call these APIs. This is fixed by the fabric nodejs sdk by design and I am not able to change it, which could be a problem for our specific scenario now. I already tested the anonymisation related chaincode and made sure it worked properly. What I needed now a chaincode "invoke" api that satisfies the requirement (e.g. without token autho). It would be great help if you could provide such an api asap. cheers.

**Comment by RunshanHu** [comment] 2017-11-03 16:37
The proposed API taking the following arguments are good with me. i.e, 
- serviceID: identifier of the requested computational service
- functionID: identifier of the function within the service to invoke
- argument: list of invocation arguments for the function to invoke

**Comment by derigo88** [comment] 2017-11-03 21:06
Runshan thanks for your work.

I'm aware of constraints that the sdk imposes, that's why I was quite
sceptical to use it and I created one from scratch.

If you want we use the "home made" sdk that I developed, as you know there
still be a bug to fix for the invoke operation, while is working fine for
the put and get operations.

Before to fix this, I must provide the new environment with two separated
VMs running different peers. This has high priority, thus I'm 100% on it
till I success.

If you want to try to fix it on your own I'm happy it, otherwise we have to
wait some days.

Furthermore, on Thursday and Friday I'll be abroad, so I don't think to be
able to work on it before the next week.

Let me know what you think.
Federico


Il 03 nov 2017 17:34, "Runshan Hu" <notifications@github.com> ha scritto:

I implemented a series of computation APIs for service ledger, a.k.a.
setupLedger (hyperledger enviroment and network setting up),
installChaincode, initChaincode and invokeChaincode. However, they all need
a json web token as a parameter every time you call these APIs. This is
fixed by the fabric nodejs sdk by design and I am not able to change it,
which could be a problem for our specific scenario now. I already tested
the anonymisation related chaincode and made sure it worked properly. What
I needed now a chaincode "invoke" api that satisfies the requirement (e.g.
without token autho). It would be great help if you could provide such an
api asap. cheers.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/sunfish-prj/Registry/issues/2#issuecomment-341757693>,
or mute the thread

**Comment by RunshanHu** [comment] 2017-11-03 23:01
Federico, thank you for your reply! Honestly, I think developing a hyperledger api from scratch by using command line things is a great idea, which requires a thorough understanding of the mechanism. However, since I am not familiar with your programs and the low level things, maybe I will spend weeks understanding it which you can fix it just in one hour. So I would suggest you finish your priority first and then proceed with the API, and I keep working on other remaining issues in RI this week. Just a reminder, I have tested the anonymisation chaincode and can make sure it works properly. So no worries about it now. When you have a ready invoke api, you can just install it on the peers and invoke the functions in it. We can do it together then! Cheers @derigo88

**Closed** 2017-11-24 20:08 UTC
Labels: enhancement
